<?php
ini_set('display_errors', 'On');
error_reporting(E_ALL^E_NOTICE);

/**
 * Implements hook_menu()
 **/
function album_clocod_menu() {
	// Menu path to show Albums.
	$items['albums'] = array(
		'title' => t('Albums'),
		'page callback' => 'albums_page',
		'access callback' => TRUE,
		'file' => 'album_clocod.pages.inc',
		'type' => MENU_CALLBACK,
	);

	// Menu path to show Album photos
	$items['albums/%'] = array(
		'title' => t('List of Album Photos'),
		'page callback' => 'album_photos_page',
		'page arguments' => array(1),
		'access callback' => TRUE,
		'file' => 'album_clocod.pages.inc',
		'type' => MENU_CALLBACK,
	);

	return $items;
}
	
